---
# tasks file for common
- name: Add group "{{ greenplum.greenplum_admin_user }}" to remote server
  group:
   name: "{{ greenplum.greenplum_admin_user }}"
   gid: 1296
   state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: create greenplum admin user
  user:
    name: "{{ greenplum.greenplum_admin_user }}"
    password: "{{ greenplum.greenplum_admin_password | password_hash('sha512', 'DvkPtCtNH+UdbePZfm9muQ9pU') }}"
    groups: gpadmin,wheel

- name: Update Yum repo list
  shell: yum updateinfo
  changed_when: false
  args:
    warn: no

- name: Install git, vim, tmux & unzip
  yum:
    name:
      - git
      - vim
      - tmux
      - unzip
    state: present
    update_cache: true

- name: Checkout VIM modules
  become: yes
  become_user: "{{ greenplum.greenplum_admin_user }}"
  git:
    repo: 'https://github.com/amix/vimrc.git'
    dest: /home/{{ greenplum.greenplum_admin_user }}/.vim_runtime

- name: Install VIM config
  shell: sh /home/{{ greenplum.greenplum_admin_user }}/.vim_runtime/install_awesome_vimrc.sh
  become: yes
  become_user: "{{ greenplum.greenplum_admin_user }}"
  register: out
  args:
    creates: /home/"{{ greenplum.greenplum_admin_user }}"/.vimrc

- name: Enable IPV6 route advertisements (/etc/sysconfig/network updated on reboot)
  replace:
    path: /usr/lib/python2.7/site-packages/cloudinit/net/sysconfig.py
    regexp: 'IPV6_AUTOCONF=no'
    replace: 'IPV6_AUTOCONF=yes'

- name: Update /etc/hosts
  copy:
    src: files/etchosts
    dest: /etc/hosts
    mode: '0644'

- name: Create files directory
  file:
    path: files
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy PEM file
  copy:
    src: files/gp_dev.pem
    dest: /home/{{ ansible_user }}/files/gp_dev.pem
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'


