---
# tasks file for dwdatanode
- name: Create XFS data primary segmewnt data partitions
  community.general.parted:
    device: /dev/nvme{{ item }}n1
    number: 1
    state: present
    fs_type: xfs
  with_sequence: start=1 end={{ greenplum.segments_per_host }}

- name: Create XFS segment data filesystems
  community.general.filesystem:
    fstype: xfs
    opts: -L DATA{{ item }}
    dev: /dev/nvme{{ item }}n1
  with_sequence: start=1 end={{ greenplum.segments_per_host }}

- name: Mount segment data filesystems by label
  ansible.posix.mount:
    path: /data{{ item }}
    src: LABEL=DATA{{ item }}
    fstype: xfs
    opts: rw,noatime,nobarrier,nodev,inode64,allocsize=16m
    state: mounted
  with_sequence: start=1 end={{ greenplum.segments_per_host }}
  
- name: Set the device read-ahead (blockdev) value to 16384
  lineinfile:
    path: /etc/rc.d/rc.local
    state: present
    line: /sbin/blockdev --setra 16384 /dev/nvme{{ item }}n1
    mode: a+x
  with_sequence: start=1 end={{ greenplum.segments_per_host }}

- name: Set the Disk I/O scheduler
  shell: grubby --update-kernel=ALL --args="elevator=deadline"

- name: Disable Transparent Huge Pages (THP)
  shell: grubby --update-kernel=ALL --args="transparent_hugepage=never"

- name: Make segment data filesystems world-writable
  file:
    path: /data{{ item }}
    state: directory
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0777'
  with_sequence: start=1 end={{ greenplum.segments_per_host }}

- name: Create segment data directories
  file:
    path: /data{{ item[0] }}/gpdb/{{ item[1] }}
    state: directory
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0777'
  with_nested:
    - "{{ range(1,greenplum.segments_per_host+1)|list }}"
    - [ 'primary', 'mirror' ]

