---
- hosts: all
  gather_facts: False
  tasks:

- name: data warehouse master configuration
  gather_facts: False
  hosts: dwmaster
  become: yes
  become_method: sudo
  roles:
    - dwmaster

- name: data warehouse standby configuration
  gather_facts: False
  hosts: dwstandby
  become: yes
  become_method: sudo
  roles:
    - dwstandby

- name: data warehouse data node configuration
  gather_facts: False
  hosts: dwdatanodes
  become: yes
  become_method: sudo
  roles:
    - dwdatanode

