---
# tasks file for dwcommon
- name: Disable SELinux
  selinux:
    state: disabled
  notify: Reboot host and wait for it to restart

- name: Create .ssh directory
  file:
    path: /home/{{ greenplum.greenplum_admin_user }}/.ssh
    state: directory
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0700'
  
- name: Copy private key to ansible host
  copy:
    src: files/id_rsa
    dest: /home/{{ greenplum.greenplum_admin_user }}/.ssh/id_rsa
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0600'

- name: Copy public key to ansible host
  copy:
    src: files/id_rsa.pub
    dest: /home/{{ greenplum.greenplum_admin_user }}/.ssh/id_rsa.pub
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0600'

- name: Copy authorzed_keys to ansible host
  copy:
    src: files/authorized_keys
    dest: /home/{{ greenplum.greenplum_admin_user }}/.ssh/authorized_keys
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0600'

- name: Set GPDB nproc, nofile and core limits
  copy:
    src: "{{ role_path }}/files/gpdb-limits.conf"
    dest: /etc/security/limits.d

- name: Set GPDB sysctl.conf values
  notify: Reload systemctl
  copy:
    src: "{{ role_path }}/files/gpdb-sysctl.conf"
    dest: /etc/sysctl.conf

- name: Create core file directory if it does not exist
  file:
    path: /var/crash/cores
    state: directory
    mode: '0777'

- name: Copy TanzuNet downloaded file(s)
  synchronize:
    src: /home/{{ greenplum.greenplum_admin_user }}/pivnet_files
    dest: /home/{{ greenplum.greenplum_admin_user }}
  delegate_to: mdw_ipv4

- name: Install GPDB pivnet_files/greenplum-db-{{ greenplum.v6.pivnet_release_version }}-rhel7-x86_64.rpm
  yum:
    name: "/home/{{ greenplum.greenplum_admin_user }}/pivnet_files/greenplum-db-{{ greenplum.v6.pivnet_release_version }}-rhel7-x86_64.rpm"
    state: present

- name: Create .bashrc
  copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "/home/{{ greenplum.greenplum_admin_user }}/.bashrc"
    owner: "{{ greenplum.greenplum_admin_user }}"
    group: "{{ greenplum.greenplum_admin_user }}"
    mode: '0600'

- name: Set host
  hostname:
    name: "{{ inventory_hostname }}"


